### ISSUE TITLE
windows, macos: install source package, if binary is not available

### ISSUE THREAD

**Issue by gaborcsardi** [r-hub/rhub#123]
maybe a remotes bug?

**Comment by jalazawa** [comment]
I think I have a bug related to this issue, I asked a question in stackoverflow [here](https://stackoverflow.com/questions/48948424/rhub-how-can-i-force-the-installation-of-data-table-in-rhub). 

Maybe this issue is also related with #97 and #109, all these issues are about this error "package not available". 

My initial question is : How to tell to rhub that I want to install this **package** with source ? I think it's not possible now.

**Comment by gaborcsardi** [comment]
> My initial question is : How to tell to rhub that I want to install this package with source ?

You can't, currently.

**Comment by gaborcsardi** [comment]
This is fixed now, via https://github.com/r-lib/remotes/issues/128 and https://github.com/r-hub/wincheck/issues/12

**Comment by gaborcsardi** [comment]
Actually, not yet fixed for macos.

**Comment by gaborcsardi** [comment]
Fixed on macos as well, via https://github.com/r-hub/macoscheck/issues/11
