### ISSUE TITLE
netcdf

### ISSUE THREAD

**Issue by jpritikin** [r-hub/rhub#131]
Will it be possible to build the ncdf4 package that depends on HDF5 and NetCDF libraries?

**Comment by maelle** [comment]
:wave: @jpritikin on Linux platforms of the R-hub builder it should already be possible if you've specified the dependencies in the `SystemRequirements` field of `DESCRIPTION`, because these platforms use `sysreqsdb` to recognize and install system dependencies, and I see entries for the two libraries you mention. See [`sysreqsdb` README](https://github.com/r-hub/sysreqsdb) for more info.

**Comment by maelle** [comment]
To be clear, the `DESCRIPTION` I mentioned is `ncdf4`'s, and from what I see it only mentions netcdf https://cran.r-project.org/web/packages/ncdf4/index.html

**Comment by jpritikin** [comment]
Hm, thanks. It turns out that I've taken a different approach, but I'll keep your hints in mind for the future.
