### ISSUE TITLE
`rhub::check_on_fedora()` build doesn't support transparency in `ggplot2` plots

### ISSUE THREAD

**Issue by IndrajeetPatil** [r-hub/rhub#159]
All my package functions produce `ggplot2` plots where the `geoms` have been rendered with some level of transparency (e.g., `alpha = 0.3`). So when I run `rhub::check_on_fedora()`,  I get the following error while building vignettes for my package: 

![image](https://user-images.githubusercontent.com/11330453/46081942-cc6a9a80-c16b-11e8-9de6-be4c8097d899.png)
 
Maybe this can be resolved by installing the Cairo graphics device for this build first?
http://tinyheero.github.io/2015/09/15/semi-transparency-r.html

**Comment by maelle** [comment]
:wave: @IndrajeetPatil! There's the transparency warning, but the error is due to missing fonts which should have been solved by a recent commit of @gaborcsardi's to the Linux dockerfiles, "Fedora, Ubuntu and Debian images have more X11 fonts now (once deployed in a couple of minutes). Hopefully this is enough."

**Comment by gaborcsardi** [comment]
See https://github.com/r-hub/rhub/issues/188#issuecomment-471965639
