### ISSUE TITLE
Can one cancel a build?

### ISSUE THREAD

**Issue by maelle** [r-hub/rhub#164]
Or not yet? Thanks :-)

**Comment by gaborcsardi** [comment]
No, can't. Not a very useful feature for the user I suppose.

**Comment by jackwasey** [comment]
I would like to see this (as a plain user). I occasionally fire off an rhub build request, then immediately find and fix an issue: I'd like to save the rhub resources, and issue a cancellation, and have this status code recorded as such, rather than an error. This is more likely for slower checks like valgrind and (hoping in the future) gctorture.
