### ISSUE TITLE
Include the package-Ex.Rout file in rhub results

### ISSUE THREAD

**Issue by zhanxw** [r-hub/rhub#186]
This is a feature suggestion.

When I checked my package `seqminer` using `rhub::check_with_valgrind("seqminer")`, the check result is OK. But this does not provide the valgrind errors reported in the file `seqminer.Rcheck/seqminer-Ex.Rout`.

Can rhub provide a way to retrieve this file?
For example, when I ran `result <- rhub::check_with_valgrind("seqminer")`, I can use `result$output_file` to read the content of `seqminer-Ex.Rout`.

**Comment by maelle** [comment]
related to #197

**Comment by helix123** [comment]
While this issue seems to be about the package `rhub`, I would like to add that it would be very convenient to have the file `package-Ex.Rout` placed in the respective `artifacts` directory of the server (https://artifacts.r-hub.io).

The `package-Ex.Rout` file is a real value add for testing: Running all examples and having their output compared to a reference guards against a lot of unintentional changes. Thus, making available this output artifact would be highly appreciated.

**Comment by gaborcsardi** [comment]
This issue is about the previous R-hub system, it does not apply to the new system, so I am closing it now. Please see https://r-hub.github.io/rhub/ for the new system, R-hub v2.
