### ISSUE TITLE
Could not fetch image when building vignette

### ISSUE THREAD

**Issue by traversc** [r-hub/rhub#274]
I had the following error while building the vignette.  Can it be fixed?

```
* checking re-building of vignette outputs ... WARNING
Error(s) in re-building vignettes:
--- re-building 'vignette.rmd' using rmarkdown
Could not fetch https://travis-ci.org/traversc/qs.svg
HttpExceptionRequest Request {
  host                 = "travis-ci.org"
  port                 = 443
  secure               = True
  requestHeaders       = []
  path                 = "/traversc/qs.svg"
  queryString          = ""
  method               = "GET"
  proxy                = Nothing
  rawBody              = False
  redirectCount        = 10
  responseTimeout      = ResponseTimeoutDefault
  requestVersion       = HTTP/1.1
}
```

**Comment by gaborcsardi** [comment]
This is a bug in pandoc. Which builder did you see this on?

**Comment by traversc** [comment]
The e-mail says 

Platform: | Debian Linux, R-devel, clang, ISO-8859-15 locale

I used the default.

**Comment by cderv** [comment]
Just stumbling upon this while looking at Pandoc version and rhub. 

FWIW this type of issue arises when an image cannot be found online by Pandoc during conversion when `---self-contained` is used (which is the default for vignette).

Since Pandoc 2.18, this will now be a warning only in Pandoc when this happens which will no more prevent rendering.

**Comment by gaborcsardi** [comment]
This issue is about the previous R-hub system, it does not apply to the new system, so I am closing it now. Please see https://r-hub.github.io/rhub/ for the new system, R-hub v2.
