### ISSUE TITLE
individual bug reports

### ISSUE THREAD

**Issue by romainfrancois** [r-hub/rhub#41]
Sometimes when people report bugs on a package, the resolution is actually "well it works now on the development version, ..." 

Could `rhub` be somehow used as a way to report bugs as reprexs . 

A hacky way I guess would be to encapsulate the piece of code that shows the bug as a package and then send this to `rhub`.

**Comment by gaborcsardi** [comment]
Great idea!

You would submit the reprex, and r-hub would run it on various R versions or platforms, and show you the result.

I'll talk to the ISC about it.

**Comment by romainfrancois** [comment]
I can initially coin my hacky way into a separate package if that helps. And I have a name that I like for it `rhubarb`. 

But we would still get usual package results for the generated pseudo package, so maybe a lot of noise on top of the actual testing of the bug at hand. 

In a nutshell, `rhubarb` could : 
 - offer some way to write a reprex, and declare its dependencies (cran or remotes)
 - test it locally 
 - wrap it up as a package and `rhub` it. 
 - perhaps post process `rhub` results
 - prepare a github issue

Maybe this overlaps with @jennybc's `reprex` package.

**Comment by gaborcsardi** [comment]
Sounds good. An idea.

I want to have a mode on rhub that does not run the checks, but only the tests. I usually only care about `R CMD check` before CRAN submission, but otherwise I just want to run the tests. 

So your package could set up the reprex as a test case.

I would ignore that last two points for now, postprocessing rhub results can be tricky, you need to poll, the build might not start immediately, etc. So the user can just wait and check this manually. 

Opening a GH issue is also kind of messy, you need a token, etc. So in rhubarb you can just point the user to the BugReports field, or the maintainer email address, and the R-hub build.

**Comment by romainfrancois** [comment]
Sure, especially given that the `R CMD check` results are irrelevant in that case.

**Comment by gaborcsardi** [comment]
Still think this is a good idea, but other things have higher priority, so I'll so it now.
