### ISSUE TITLE
DLL 'rlang' not found: maybe not installed for this architecture?

### ISSUE THREAD

**Issue by hbaniecki** [r-hub/rhub#476]
Duplicate of https://github.com/r-lib/rlang/issues/1238 but it may be `rhub`-specific. `rlang` seems to install properly, but then proceeds to fail on r-devel Windows...  Any help would be appreciated, as it happens for a few days now.

Example: https://builder.r-hub.io/status/modelStudio_3.0.0.tar.gz-db9e3ce470ae4ce994c112900f2537b5

**Comment by gaborcsardi** [comment]
This is because CRAN R-devel binaries are x64-only, but `R CMD check` by default also runs the checks on i386. Will be fixed soon, here is a workaround for now:
```r
rhub::check(..., check_args = "--no-multiarch")
```

**Comment by hbaniecki** [comment]
@gaborcsardi thanks, it is OK using the workaround. Do you know if it will pass during CRAN checks, or do I have to wait?

**Comment by gaborcsardi** [comment]
You don't need to wait.

**Comment by hbaniecki** [comment]
Thank you

**Comment by gaborcsardi** [comment]
OK, we add `--no-multiarch` now to all R-hub R-devel Windows checks. 

This is not quite ideal, because CRAN still runs both arch, as they use their own installed packages, and they do not use CRAN binaries. 

But short of building all CRAN packages with multi-arch ourselves, there is not much we can do.
