### ISSUE TITLE
ERROR: compilation failed for package ‘bigmemory’

### ISSUE THREAD

**Issue by doccstat** [r-hub/rhub#566]
I have this [fastcpd R package](https://github.com/doccstat/fastcpd/tree/c4839546c4f633876870c6e9ac3712c8636c834e) ready to submit to CRAN. I used `cran_prep <- rhub::check_for_cran()`.

The build is successful at https://builder.r-hub.io/status/fastcpd_0.5.7.tar.gz-1b1c644050644d378e8a225a4ca44fac and https://builder.r-hub.io/status/fastcpd_0.5.7.tar.gz-30d53ed98bda48c3b17e56d2488a2187

But failed at https://builder.r-hub.io/status/fastcpd_0.5.7.tar.gz-48f11b231fee49c69088ca412e51e681#L637

The failure comes from the fact that `bigmemory` can not be installed since `-luuid` can not be found, while `uuid` is installed based on the logs.

**Comment by gaborcsardi** [comment]
That seems like a bug in the bigmemory package to me, it is trying to link to the uuid package, but you cannot link to another R package like that.

It only works on some Linux systems by accident, if another `libuuid` library happens to be available in the system. 

Seems like it is fixed already in the dev version of the package, but they haven't had another release since then: https://github.com/kaneplusplus/bigmemory/commit/177c761821a2f5d8c48cb88a9dc344ed47dc8697

**Comment by gaborcsardi** [comment]
This issue is about the previous R-hub system, it does not apply to the new system, so I am closing it now. Please see https://r-hub.github.io/rhub/ for the new system, R-hub v2.

**Comment by gaborcsardi** [comment]
This issue is about the previous R-hub system, it does not apply to the new system, so I am closing it now. Please see https://r-hub.github.io/rhub/ for the new system, R-hub v2.
