### ISSUE TITLE
Rhub error (utf-8. error in query)

### ISSUE THREAD

**Issue by NakarinP** [r-hub/rhub#591]
Yesterday, I used devtools::check_rhub() and it worked just fine. Today, I did the same thing to check the same package without any edit, but I got this following error.

"no encoding supplied: defaulting to utf-8. error in query("get platforms", as = "text") : rhub error"

Can you help me fix this issue. I have checked the old issues, it happened before and it might be from the Rhub side?

Thanks,

Nakarin

**Comment by gaborcsardi** [comment]
Unfortunately this is an error that we won't fix, because we are transitioning to a new system, see the REAMDE in this repository.

For now you'll have to install the package from GitHub, e.g.
```
pak::pkg_install("r-hub/rhub")
```
or 
```
remotes::install_github("r-hub/rhub")
```
and then see the manual, especially 
https://r-hub.github.io/rhub/dev/articles/rhubv2.html

I am sorry for the abrupt change!

**Comment by NakarinP** [comment]
> Unfortunately this is an error that we won't fix, because we are transitioning to a new system, see the REAMDE in this repository.
> 
> For now you'll have to install the package from GitHub, e.g.
> 
> ```
> pak::pkg_install("r-hub/rhub")
> ```
> 
> or
> 
> ```
> remotes::install_github("r-hub/rhub")
> ```
> 
> and then see the manual, especially https://r-hub.github.io/rhub/dev/articles/rhubv2.html
> 
> I am sorry for the abrupt change!

Thanks!
