### ISSUE TITLE
Show badge link for add in README.md when test finished.

### ISSUE THREAD

**Issue by jhk0530** [r-hub/rhub#608]
Hi, nice work for this rhub package.

Since I'm not familiar with github action, I really and really appreciate for this easy-to-use R CMD CHECK functions.

Here is just small suggestion.

I really like message : Check started.... See <LINK> for live output !

and I think it's good to add another message, 

You can add badge in your readme.md <LINK> like this 

![r-hub](https://github.com/jhk0530/gemini.R/actions/workflows/rhub.yaml/badge.svg) 
which is from one of my R package that used "rhub" !! 

and this badge link can be 

```
![r-hub](https://github.com/<ACCOUNT>/<REPOSITORY>/actions/workflows/rhub.yaml/badge.svg)
```

I believe `rhub` has already information about account and repository. 

I'm not sure how can I contribute with code here, So just mention this small idea only.

Thanks again !!

**Comment by gaborcsardi** [comment]
Hmmm, the thing is, usually these badges show the current state of the repo. On the other hand, since the R-hub workflow typically triggered manually, so typically such a badge would not show the current status.

Of course you run the R-hub workflow for every commit, if you like. Or, you can create a badge, even if it does not always show the status of the latest commit. But I am not entirely sure if we need to encourage this in the rhub package.

**Comment by jhk0530** [comment]
As you said, the R-hub workflow is triggered manually using the rhub_check() function, so I didn't realize that badges don't guarantee the latest commit status.

I agree with you that we don't need that functionality in the R-hub package.  

Thanks
