### ISSUE TITLE
Error with clang18 in igraph

### ISSUE THREAD

**Issue by krlmlr** [r-hub/rhub#613]
```
flang-new: error: unknown argument '-fvisibility=hidden'; did you mean '-Xclang -fvisibility=hidden'?
```

https://github.com/igraph/rigraph/actions/runs/9341386885/job/25708087211#step:6:75

Haven't looked closer.

**Comment by gaborcsardi** [comment]
If I follow that suggestion I get
```
flang-new-18 -Xclang -fvisibility=hidden -fpic  -O2 -pedantic -c vendor/arpack/dgetv0.f -o vendor/arpack/dgetv0.o
flang-new: error: unknown argument '-Xclang'; did you mean '-Xflang'?
flang-new: error: unknown argument '-fvisibility=hidden'; did you mean '-Xclang -fvisibility=hidden'?
```

The problem is that R was build with a Fortran compiler that supports `-fvisibility=hidden`, but then we use `flang-new-18` to install packages, which does not. AFAICT there is no way to use `-fvisibility=hidden` with `flang-new-18` now, so I'll remove that flag via our local `Makevars`.

**Comment by gaborcsardi** [comment]
Should be good tomorrow (Wednesday).
