### ISSUE TITLE
Failed build on windows r-devel

### ISSUE THREAD

**Issue by gaborcsardi** [r-hub/rhub#67]
```
library("rhub")
check("robustarima_0.2.5.tar.gz", platform="windows-x86_64-devel")
```
The error (from the rhub email):

```
Running examples in 'robustarima-Ex.R' failed

The error most likely occurred in:
> ### Title: Outliers Extraction for an <code>arima.rob</code> Object
> ### Aliases: outliers
> ### Keywords: ts
> 
> ### ** Examples
> 
> frip.rr <- arima.rob(log(frip.dat) ~ 1, p=2, d=1, iter=2)
Error in c(out2$outlier.positions, object[[i]]$outlier.positions) : 
  could not find symbol "recursive" in environment of the generic function
Calls: arima.rob -> outliers.combine -> c
Execution halted
> ### Name: outliers
** running examples for arch 'x64' ... ERROR
The error most likely occurred in:

> ### Name: outliers
> ### Title: Outliers Extraction for an <code>arima.rob</code> Object
> ### Aliases: outliers
> ### Keywords: ts
> 
> ### ** Examples
> 
> frip.rr <- arima.rob(log(frip.dat) ~ 1, p=2, d=1, iter=2)
Error in c(out2$outlier.positions, object[[i]]$outlier.positions) : 
  could not find symbol "recursive" in environment of the generic function
Calls: arima.rob -> outliers.combine -> c
```

Could there be a problem with the R-hub R build for windows-x86_64-devel?

The robustarima_0.2.5.tar.gz file can be found on CRAN (https://cran.r-project.org/package=robustarima)

**Comment by jpearson0525** [comment]
I have another case of a failed build on the windows-x86_64-devel platform.  In this case, It appears the platform does not have a copy of the current CRAN library and must download each element required.  After 10 minutes the build aborts due to time.  

Enclosed is listing returned from the devel platform and a listing returned from the oldRelease platform.  Not the time on the oldrel platform is around 2 minutes.

My big question is will I have the same problem when I release the package on the CRAN windows-x86_64-devel platform?

Cheers, Jim

-  Uploading package
-  Preparing build, see status at
   http://builder.r-hub.io/status/satscanMapper_1.0.0.tar.gz-1cde9722b3b64ccc9c9bc63671d1de6c

-  Build started
-  Creating new user
-  Downloading and unpacking package file
-  Querying package dependencies
-  Installing package dependencies

Finished: ABORTED
[1] "windows-x86_64-devel"

-- satscanMapper 1.0.0: ABORTED

  Build ID:   satscanMapper_1.0.0.tar.gz-1cde9722b3b64ccc9c9bc63671d1de6c
  Platform:   Windows Server 2008 R2 SP1, R-devel, 32/64 bit
  Submitted:  10.8s ago
  Build time: 11m 3.4s    <------------- normal time is about 2-3 minutes.

> Build failed during preparation or aborted

[...]
CommonProgramFiles             C:\Program Files\Common Files                   
CommonProgramFiles(x86)        C:\Program Files (x86)\Common Files             
CommonProgramW6432             C:\Program Files\Common Files                   
COMPUTERNAME                   WIN-BUILDER-1                                   
ComSpec                        C:\Windows\system32\cmd.exe                     
FP_NO_HOST_CHECK               NO                                              
home                           C:\Users\USERjwkdSFvnig                         
NUMBER_OF_PROCESSORS           2                                               
OS                             Windows_NT                                      
Path                           c:\Rtools33\bin;c:\Rtools33\gcc-4.6.3\bin;C:\...
PATHEXT                        .COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;....
PROCESSOR_ARCHITECTURE         AMD64                                           
PROCESSOR_IDENTIFIER           Intel64 Family 6 Model 45 Stepping 7, Genuine...
PROCESSOR_LEVEL                6                                               
PROCESSOR_REVISION             2d07                                            
ProgramData                    C:\ProgramData                                  
ProgramFiles                   C:\Program Files                                
ProgramFiles(x86)              C:\Program Files (x86)                          
ProgramW6432                   C:\Program Files                                
PSModulePath                   C:\Users\Default\Documents\WindowsPowerShell\...
PUBLIC                         C:\Users\Public                                 
SystemDrive                    C:                                              
SystemRoot                     C:\Windows                                      
TEMP                           C:\Windows\TEMP                                 
TMP                            C:\Windows\TEMP                                 
USERDOMAIN                     WIN-BUILDER-1                                   
USERNAME                       USERjwkdSFvnig                                  
USERPROFILE                    C:\Users\USERjwkdSFvnig                         
windir                         C:\Windows                                      
windows_tracing_flags          3                                               
windows_tracing_logfile        C:\BVTBin\Tests\installpackage\csilogfile.log   

setting _R_CHECK_FORCE_SUGGESTS_ to false

> source('https://bioconductor.org/biocLite.R')

Installing package into 'C:/Users/USERjwkdSFvnig/R'
(as 'lib' is unspecified)

### Why is bioconductor group involved??  not a dependency??

trying URL 'https://bioconductor.org/packages/3.5/bioc/bin/windows/contrib/3.4/BiocInstaller_1.26.0.zip'

Content type 'application/zip' length 127773 bytes (124 KB)

==================================================

downloaded 124 KB

package 'BiocInstaller' successfully unpacked and MD5 sums checked

The downloaded binary packages are in
        C:\Users\USERjwkdSFvnig\TEMP\RtmpMfxleh\downloaded_packages
> 
> 

Bioconductor version 3.5 (BiocInstaller 1.26.0), ?biocLite for help

A Querying package dependencies

setting _R_CHECK_FORCE_SUGGESTS_ to false

> source('install-github.R')$value('mangothecat/remotes')

Downloading GitHub repo mangothecat/remotes@master
Installing package into 'C:/Users/USERjwkdSFvnig/R'
(as 'lib' is unspecified)
* installing *source* package 'remotes' ...

** R
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
> 
> 

*** arch - i386
*** arch - x64
* DONE (remotes)

â Installing package dependencies

setting _R_CHECK_FORCE_SUGGESTS_ to false

> remotes::install_local('satscanMapper', dependencies = TRUE, INSTALL_opts = '--build')
Installing 14 packages: magrittr, maptools, RColorBrewer, rgdal, SeerMapper, SeerMapper2010East, SeerMapper2010Regs, SeerMapper2010West, SeerMapperEast, SeerMapperRegs, SeerMapperWest, sp, stringi, stringr
package 'magrittr' successfully unpacked and MD5 sums checked
package 'maptools' successfully unpacked and MD5 sums checked
package 'RColorBrewer' successfully unpacked and MD5 sums checked
package 'rgdal' successfully unpacked and MD5 sums checked
package 'SeerMapper' successfully unpacked and MD5 sums checked
package 'SeerMapper2010East' successfully unpacked and MD5 sums checked
package 'SeerMapper2010Regs' successfully unpacked and MD5 sums checked
package 'SeerMapper2010West' successfully unpacked and MD5 sums checked
package 'SeerMapperEast' successfully unpacked and MD5 sums checked
package 'SeerMapperRegs' successfully unpacked and MD5 sums checked
package 'SeerMapperWest' successfully unpacked and MD5 sums checked
package 'sp' successfully unpacked and MD5 sums checked
package 'stringi' successfully unpacked and MD5 sums checked
package 'stringr' successfully unpacked and MD5 sums checked
Installing package into 'C:/Users/USERjwkdSFvnig/R'
(as 'lib' is unspecified)

* installing *source* package 'satscanMapper' ...

** R
** data
** inst
** byte-compile and prepare package for lazy loading
Build timed out (after 10 minutes). Marking the build as aborted.
Build was aborted


==== windows oldrelease 

-  Uploading package
-  Preparing build, see status at
   http://builder.r-hub.io/status/satscanMapper_1.0.0.tar.gz-9aa7e91997334290a981c71e60d50eb6
-  Build started
-  Creating new user
-  Downloading and unpacking package file
-  Querying package dependencies
-  Installing package dependencies

-  Running R CMD check
   setting _R_CHECK_FORCE_SUGGESTS_ to false
-  using log directory 'C:/Users/USERHLwnfFUuOP/satscanMapper.Rcheck'
-  using R version 3.3.3 (2017-03-06)
-  using platform: x86_64-w64-mingw32 (64-bit)
-  using session charset: ISO8859-1
?  checking for file 'satscanMapper/DESCRIPTION'
-  checking extension type ... Package
-  this is package 'satscanMapper' version '1.0.0'
?  checking package namespace information
?  checking package dependencies
?  checking if this is a source package
?  checking if there is a namespace
?  checking for executable files
?  checking for hidden files and directories
?  checking for portable file names
?  checking whether package 'satscanMapper' can be installed
?  checking installed package size
?  checking package directory
?  checking DESCRIPTION meta-information
?  checking top-level files
?  checking for left-over files
?  checking index information
?  checking package subdirectories
?  checking R files for non-ASCII characters
?  checking R files for syntax errors
?  checking whether the package can be loaded
?  checking whether the package can be loaded with stated dependencies
?  checking whether the package can be unloaded cleanly
?  checking whether the namespace can be loaded with stated dependencies
?  checking whether the namespace can be unloaded cleanly
?  checking loading without being on the library search path
?  checking dependencies in R code
?  checking S3 generic/method consistency
?  checking replacement functions
?  checking foreign function calls
?  checking R code for possible problems
?  checking Rd files
?  checking Rd metadata
?  checking Rd cross-references
?  checking for missing documentation entries
?  checking for code/documentation mismatches
?  checking Rd \usage sections
?  checking Rd contents
?  checking for unstated dependencies in examples
?  checking contents of 'data' directory
?  checking data for non-ASCII characters
?  checking data for ASCII and uncompressed saves
?  checking examples
?  checking PDF version of manual

-- 0 errors ? | 0 warnings ? | 0 notes ?
-  Cleaning up files and user
    
[1] "windows-x86_64-oldrel"

-- satscanMapper 1.0.0: OK

  Build ID:   satscanMapper_1.0.0.tar.gz-9aa7e91997334290a981c71e60d50eb6
  Platform:   Windows Server 2008 R2 SP1, R-oldrel, 32/64 bit
  Submitted:  1.9s ago
  Build time: 2m 8.1s


-- R CMD check results ------------------------------------- satscanMapper 1.0.0 ----

-- 0 errors ? | 0 warnings ? | 0 notes ?

**Comment by markvanderloo** [comment]
Just to add another case (maybe helpful, maybe not). I also get an ABORTED message on rhub-Windows while everything runs fine locally (ubuntu 16.04) and rhub/linux, (release/r-devel)

[https://builder.r-hub.io/status/dcmodify_0.1.0.tar.gz-69340c9c113e4904a144694502417580](https://builder.r-hub.io/status/dcmodify_0.1.0.tar.gz-69340c9c113e4904a144694502417580)

below is a dump of the log.

```
Preparing

   1#> Started by user r-hub Jenkins admin
   2#> Building remotely on win-builder-1.win-builder-1-58fa33gp.b6.internal.cloudapp.net-cf50e36a (slave swarm windows) in workspace C:\Users\rhub\Documents\workspace\dcmodify_0.1.0.tar.gz-69340c9c113e4904a144694502417580
   3#> [dcmodify_0.1.0.tar.gz-69340c9c113e4904a144694502417580] $ powershell.exe -NonInteractive -ExecutionPolicy ByPass "& 'C:\Users\rhub\AppData\Local\Temp\2\hudson3523701694030585327.ps1'"
   4#> StatusCode : 200
   5#> StatusDescription : OK
   6#> Content : {"status":"ok"}
   7#> RawContent : HTTP/1.1 200 OK
   8#> Transfer-Encoding: chunked
   9#> Connection: keep-alive
  10#> Vary: Accept-Encoding
  11#> Alternate-Protocol: 443:npn-spdy/2
  12#> Content-Type: application/json
  13#> Date: Fri, 06 Oct 2017 07:47:33 GMT
  14#> Set...
  15#> Forms : {}
  16#> Headers : {[Transfer-Encoding, chunked], [Connection, keep-alive],
  17#> [Vary, Accept-Encoding], [Alternate-Protocol,
  18#> 443:npn-spdy/2]...}
  19#> Images : {}
  20#> InputFields : {}
  21#> Links : {}
  22#> ParsedHtml : System.__ComObject
  23#> RawContentLength : 15
  24#> VERBOSE: Checking dcmodify_0.1.0.tar.gz-69340c9c113e4904a144694502417580
Creating new user

  26#> VERBOSE: Copy local software...
  27#> VERBOSE: Creating new user...
  28#> VERBOSE: Creating home directory...
Downloading and unpacking package file

  30#> VERBOSE: Downloading
  31#> http://builder.r-hub.io/file/1d41b669e00745658c01021e30aff62d
  32#> VERBOSE: GET http://builder.r-hub.io/file/1d41b669e00745658c01021e30aff62d with
  33#> 0-byte payload
  34#> VERBOSE: received 12752-byte response of content type application/octet-stream
  35#> VERBOSE: Extracting dcmodify_0.1.0.tar.gz
  36#> VERBOSE: Setting home directory permissions...
  37#> VERBOSE: Getting R version from symbolic name...
  38#> VERBOSE: GET http://rversions.r-pkg.org/r-release-win with 0-byte payload
  39#> VERBOSE: received 147-byte response of content type application/json
  40#> VERBOSE: Starting sub-process as new user...
  41#> Name Value
  42#> ---- -----
  43#> ALLUSERSPROFILE C:\ProgramData
  44#> CommonProgramFiles C:\Program Files\Common Files
  45#> CommonProgramFiles(x86) C:\Program Files (x86)\Common Files
  46#> CommonProgramW6432 C:\Program Files\Common Files
  47#> COMPUTERNAME WIN-BUILDER-1
  48#> ComSpec C:\Windows\system32\cmd.exe
  49#> FP_NO_HOST_CHECK NO
  50#> home C:\Users\USERZBsmJrjwyO
  51#> NUMBER_OF_PROCESSORS 2
  52#> OS Windows_NT
  53#> Path c:\Rtools33\bin;c:\Rtools33\gcc-4.6.3\bin;C:\...
  54#> PATHEXT .COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;....
  55#> PROCESSOR_ARCHITECTURE AMD64
  56#> PROCESSOR_IDENTIFIER Intel64 Family 6 Model 45 Stepping 7, Genuine...
  57#> PROCESSOR_LEVEL 6
  58#> PROCESSOR_REVISION 2d07
  59#> ProgramData C:\ProgramData
  60#> ProgramFiles C:\Program Files
  61#> ProgramFiles(x86) C:\Program Files (x86)
  62#> ProgramW6432 C:\Program Files
  63#> PSModulePath C:\Users\Default\Documents\WindowsPowerShell\...
  64#> PUBLIC C:\Users\Public
  65#> SystemDrive C:
  66#> SystemRoot C:\Windows
  67#> TEMP C:\Windows\TEMP
  68#> TMP C:\Windows\TEMP
  69#> USERDOMAIN WIN-BUILDER-1
  70#> USERNAME USERZBsmJrjwyO
  71#> USERPROFILE C:\Users\USERZBsmJrjwyO
  72#> windir C:\Windows
  73#> windows_tracing_flags 3
  74#> windows_tracing_logfile C:\BVTBin\Tests\installpackage\csilogfile.log
  75#> setting _R_CHECK_FORCE_SUGGESTS_ to false
  76#> Exception calling "Start" with "0" argument(s): "The system cannot find the
  77#> file specified"
  78#> At C:\Users\USERZBsmJrjwyO\slave.ps1:113 char:5
  79#> + [void]$Process.Start()
  80#> + ~~~~~~~~~~~~~~~~~~~~~~
  81#> + CategoryInfo : NotSpecified: (:) [], MethodInvocationException
  82#> + FullyQualifiedErrorId : Win32Exception
  83#>
  84#> Exception calling "BeginOutputReadLine" with "0" argument(s): "StandardOut has
  85#> At C:\Users\USERZBsmJrjwyO\slave.ps1:116 char:5
  86#> not been redirected or the process hasn't started yet."
  87#> + $Process.BeginOutputReadLine()
  88#> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  89#> + CategoryInfo : NotSpecified: (:) [], MethodInvocationException
  90#> + FullyQualifiedErrorId : InvalidOperationException
  91#>
  92#> Exception calling "BeginErrorReadLine" with "0" argument(s): "StandardError
  93#> has not been redirected."
  94#> At C:\Users\USERZBsmJrjwyO\slave.ps1:117 char:5
  95#> + $Process.BeginErrorReadLine()
  96#> + CategoryInfo : NotSpecified: (:) [], MethodInvocationException
  97#> + FullyQualifiedErrorId : InvalidOperationException
  98#>
  99#> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 100#> Build timed out (after 10 minutes). Marking the build as aborted.
 101#> Build was aborted
 102#> Pinging https://builder.r-hub.io/build/ABORTED/dcmodify_0.1.0.tar.gz-69340c9c113e4904a144694502417580/2017-10-06T07:57:50Z
 103#> {"status":"ok"}
 104#> Finished: ABORTED
```

**Comment by gaborcsardi** [comment]
Should be OK now, please try.

**Comment by markvanderloo** [comment]
Confirmed. Thanks!

**Comment by gaborcsardi** [comment]
robustarima is fine as well, it was probably a temporary R-devel issue.

satscanMapper is fine as well. BioConductor is needed because CRAN packages might depend on BioConductor packages. Even if your package does not, one of its dependencies might.

**Comment by privefl** [comment]
I got this error `Build timed out (after 10 minutes). Marking the build as failed.` for the first time today.
See https://builder.r-hub.io/status/original/bigsnpr_1.1.1.tar.gz-78c032a224f64f469803d0872d1a5fb0.

Any known solution? Only temporary problem?

**Comment by gaborcsardi** [comment]
This means that `R CMD check` did not produce any output for 10 minutes. That likely means that your tests cases freeze.

**Comment by privefl** [comment]
This means that all my tests take more than 10 minutes?
Or that one individual test took more than 10 minutes?

**Comment by gaborcsardi** [comment]
`testthat.R` does not produce any output, so it is in total. It might also mean that a test case froze. Unfortunately when our scheduler kills a job, the artifacts are not saved, so we don't know where it got stuck. :(

**Comment by privefl** [comment]
I mean, I have a lot of tests, so 10 minutes may be not enough.
Is there any way to increase this timeout?

Thanks for your time.

**Comment by gaborcsardi** [comment]
It is enough to output something to the console, because the timeout is for "no output". This might not be straightforward with `R CMD check` though, because is likes to swallow the output.

One think you could do is to break up the tests into two or more directories, have multiple `testthat.R` files (`testthat-1.R`) etc. and then use `test_check(..., filter = ...)` to select the right subset. I realize that this is quite some work, but if you want to put your package on CRAN, you'll need something like this.

**Comment by privefl** [comment]
So I guess another solution would be to have `cat("")` at the beginning of all my test files :')

**Comment by eddelbuettel** [comment]
CRAN generallu does _not_ give you a ten minute budget for tests though.

**Comment by gaborcsardi** [comment]
Yeah, so `cat("")` might not work because `R CMD check` might swallow the output, more precisely, it redirects it to a file.

But @eddelbuettel is right, on CRAN your tests have to be _much_ faster.

**Comment by eddelbuettel** [comment]
I had a similar problem with the 'no stdout leading to timeout' issue at Travis, even _after_ turning their optional pulse on.  Eventually I got tired of it and switched to a custom Docker container using `ccache`.

**Comment by rmsharp** [comment]
R4.0.0 is now deployed and `x86_64-w64-mingw32 (64-bit)` is the only place I am getting a failure to build and on different runs I sometimes get different errors. Twice in a row it was `pillar` not being available as a dependency. This last failure has multiple test failing. These tests have not failed on any system before and are not failing on windows-server3-cdf9107c (slave rtools3 swarm2 rtools4 swarm windows) now.

**Comment by gaborcsardi** [comment]
@rmsharp You need to show us a log file that fails.

**Comment by gaborcsardi** [comment]
I am closing this, a very old issue, new errors have not much to do with the original one.
